### ISSUE TITLE
请问一下user agent模块从哪里获得？

### ISSUE THREAD

**Issue by jhgfkdj** [WuLC/GoogleImagesDownloader#1]
@WuLC 你好，请问一下您的代码中的用户代理模块是从哪里获取的？我自定义写了几个，但是感觉不全，想参详一下您的写法。谢谢！

**Comment by WuLC** [comment]
这个有现成的模块了，可以直接通过 pip 安装， `pip install user_agent`

**Comment by jhgfkdj** [comment]
谢谢！
