### ISSUE TITLE
Could you please support Chinese input ？

### ISSUE THREAD

**Issue by pyknife** [WuLC/GoogleImagesDownloader#2]
When I try to input Chinese，errors happened.

**Comment by WuLC** [comment]
You may pull the code  and try again, it works with Chinese and Japanese in python 3, and it should work with other language too.

**Comment by volcanoxs** [comment]
请问博主。为什么运行后一张图片都没存下来。。在我装火狐浏览器之前运行也不会报错？菜鸟一个，还请见谅这个白痴问题
