### ISSUE TITLE
DOM changed, code fix.

### ISSUE THREAD

**Issue by Catadanna** [WuLC/GoogleImagesDownloader#4]
Hallo, 

The DOM changed since the last version of this code.
Therefore, in `download_with_urllib.py` you should replace line 66 by : 

`link_list = re.findall('src="(.*?)"', page_content)`

Cheers.

**Comment by anhnhatuel** [comment]
Thanks!

**Comment by WuLC** [comment]
@Catadanna Could you please submit a pull request for this?

**Comment by Catadanna** [comment]
@WuLC: Done
